



"use client";

import { useState, type ReactNode } from "react";

type IconName =
  | "database" | "chart" | "pie" | "file" | "gear" | "cloud"
  | "shield" | "bulb" | "search" | "rocket" | "arrow" | "play"
  | "check" | "menu" | "close" | "linkedin" | "twitter" | "youtube" | "instagram";

function Icon({ name, className = "" }: { name: IconName; className?: string }) {
  const common = { className: `h-5 w-5 ${className}`, fill: "none", stroke: "currentColor", strokeWidth: 2, viewBox: "0 0 24 24", "aria-hidden": true };
  const paths: Record<IconName, ReactNode> = {
    database: <><ellipse cx="12" cy="5" rx="7" ry="3"/><path d="M5 5v7c0 1.7 3.1 3 7 3s7-1.3 7-3V5M5 12v7c0 1.7 3.1 3 7 3s7-1.3 7-3v-7"/></>,
    chart: <><path d="M4 20V10M10 20V4M16 20v-7M22 20V7"/><path d="M2 20h21"/></>, pie: <><path d="M21 12a9 9 0 1 1-9-9v9z"/><path d="M13 3a8 8 0 0 1 8 8h-8z"/></>,
    file: <><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h5M9 13h6M9 17h6"/></>, gear: <><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.1 2.1-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.04 1.56v.1h-3v-.1a1.7 1.7 0 0 0-1.04-1.56 1.7 1.7 0 0 0-1.88.34l-.06.06-2.1-2.1.06-.06A1.7 1.7 0 0 0 7 15a1.7 1.7 0 0 0-1.56-1.04h-.1v-3h.1A1.7 1.7 0 0 0 7 9.92a1.7 1.7 0 0 0-.34-1.88L6.6 8 8.7 5.9l.06.06A1.7 1.7 0 0 0 10.64 6.3 1.7 1.7 0 0 0 11.68 4.74v-.1h3v.1A1.7 1.7 0 0 0 15.72 6.3a1.7 1.7 0 0 0 1.88-.34l.06-.06L19.76 8l-.06.04a1.7 1.7 0 0 0-.34 1.88 1.7 1.7 0 0 0 1.56 1.04h.1v3h-.1A1.7 1.7 0 0 0 19.4 15z"/></>,
    cloud: <path d="M7 18a4 4 0 0 1-.8-7.92A6 6 0 0 1 17.6 8 4.5 4.5 0 1 1 18 18z"/>, shield: <path d="M12 3l7 3v5c0 4.5-3 8.2-7 10-4-1.8-7-5.5-7-10V6zM9 12l2 2 4-4"/>, bulb: <><path d="M9 18h6M10 22h4M8.5 15.5A6 6 0 1 1 15.5 15.5c-.9.8-1.5 1.5-1.5 2.5h-4c0-1-.6-1.7-1.5-2.5z"/></>,
    search: <><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></>, rocket: <><path d="M14 4c2-2 5-2 6-2 0 2 0 5-2 7l-7 7-4-4z"/><path d="M9 12 5 11l2-3 3 1M12 15l1 3-3 2-1-4M7 17l-2 2"/></>, arrow: <path d="M5 12h14M13 6l6 6-6 6"/>, play: <path d="m9 6 9 6-9 6z"/>, check: <path d="m5 12 4 4L19 6"/>,
    menu: <path d="M4 7h16M4 12h16M4 17h16"/>, close: <path d="m6 6 12 12M18 6 6 18"/>,
    linkedin: <><path d="M6 9v9M6 6v.1M10 18v-5a4 4 0 0 1 8 0v5M10 12v6"/></>, twitter: <path d="M20 7.5c-.6.3-1.2.5-1.9.6a3.2 3.2 0 0 0 1.4-1.8 6.2 6.2 0 0 1-2 .8 3.2 3.2 0 0 0-5.5 2.9A9 9 0 0 1 5.5 6.7a3.2 3.2 0 0 0 1 4.2c-.5 0-1-.2-1.5-.4a3.2 3.2 0 0 0 2.6 3.2c-.5.1-1 .2-1.5.1a3.2 3.2 0 0 0 3 2.3A6.5 6.5 0 0 1 4 17.5 9.2 9.2 0 0 0 9 19c6 0 9.3-5 9.3-9.3v-.4c.7-.4 1.2-1 1.7-1.8z"/>, youtube: <><path d="M21 12s0-4-1-5-8-1-8-1-7 0-8 1-1 5-1 5 0 4 1 5 8 1 8 1 7 0 8-1 1-5 1-5z"/><path d="m10 9 5 3-5 3z"/></>, instagram: <><rect x="4" y="4" width="16" height="16" rx="4"/><circle cx="12" cy="12" r="3.5"/><path d="M17.5 6.5h.01"/></>
  };
  return <svg {...common}>{paths[name]}</svg>;
}

const solutions = [
  ["database", "Data Integration", "Connect and unify data from multiple sources for a complete view of your business."],
  ["chart", "Advanced Analytics", "Use AI and machine learning to uncover trends, patterns, and opportunities."],
  ["pie", "Business Intelligence", "Turn complex data into clear, interactive dashboards and reports."],
  ["file", "Predictive Insights", "Anticipate future trends and make proactive decisions with AI-driven predictions."],
  ["gear", "Data Automation", "Automate data collection, processing, and reporting to save time and reduce manual effort."],
  ["cloud", "Real-Time Data", "Get up-to-date insights with real-time data pipelines and monitoring."],
  ["shield", "Data Governance", "Ensure data security, compliance, and accuracy across your organization."],
  ["bulb", "AI Data Solutions", "Custom AI-powered solutions tailored to your unique business needs."],
] as const;

const process = [["search", "Understand", "We analyze your data sources, goals, and challenges."], ["file", "Integrate", "We connect and unify your data from multiple platforms."], ["gear", "Analyze", "We apply AI and analytics to uncover meaningful insights."], ["rocket", "Visualize", "We create clear dashboards and reports for better decision-making."], ["chart", "Grow", "You take action and achieve measurable business impact."]] as const;

export default function DataIntelligencePage() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const nav = ["Home", "What AI WorksForce?", "How it Works", "Our AI Workflow", "Solutions", "Industries", "Case Studies", "Resources", "About"];
  return <main className="min-h-screen overflow-hidden bg-white font-sans text-brand-dark">
    <header className="mx-auto flex h-[62px] max-w-[1440px] items-center justify-between px-5 lg:px-8">
      <a href="#" className="leading-none"><span className="block text-[21px] font-extrabold tracking-[-1.1px] text-[#071a7a]">AI WorksForce</span><span className="ml-14 block pt-0.5 text-[8px] font-semibold tracking-tight text-brand-text">Automate. Accelerate. Grow.</span></a>
      <nav className="hidden items-center gap-6 text-[10px] font-medium text-[#415285] lg:flex">{nav.map((item) => <a key={item} className={item === "Solutions" ? "border-b-2 border-brand-blue pb-[22px] font-bold text-brand-dark" : "hover:text-brand-blue"} href="#solutions">{item}{item === "Solutions" && <span className="ml-1">⌄</span>}</a>)}</nav>
      <a href="#contact" className="hidden rounded-xl bg-gradient-to-r from-[#2016ff] to-[#082771] px-5 py-3 text-[10px] font-bold text-white shadow-lg shadow-blue-200 sm:block">Book a Free Consultation <span className="ml-1">→</span></a>
      <button onClick={() => setMobileOpen(!mobileOpen)} className="rounded-lg p-2 text-brand-dark lg:hidden" aria-label="Toggle navigation"><Icon name={mobileOpen ? "close" : "menu"}/></button>
    </header>
    {mobileOpen && <nav className="border-y border-blue-100 bg-white px-5 py-4 lg:hidden">{nav.map(n => <a key={n} href="#solutions" onClick={() => setMobileOpen(false)} className="block py-2 text-sm font-medium text-brand-text">{n}</a>)}</nav>}

    <section className="relative mx-auto max-w-[1440px] overflow-hidden rounded-b-[18px] bg-[radial-gradient(circle_at_68%_35%,#dfe2ff_0,rgba(244,248,255,.55)_26%,#fff_60%)] px-6 pb-7 pt-9 lg:px-[76px] lg:pt-10">
      <div className="absolute right-[10%] top-0 h-[420px] w-[500px] rounded-full bg-[#dce2ff]/50 blur-3xl"/>
      <div className="relative grid items-center gap-8 lg:grid-cols-[1.03fr_.97fr]">
        <div className="max-w-[570px]"><p className="mb-2 text-[10px] font-extrabold tracking-[3px] text-[#1822e5]">TURN DATA INTO OPPORTUNITIES.</p><h1 className="text-[52px] font-extrabold leading-[.9] tracking-[-3px] text-[#091a70] sm:text-[64px]">Data<br/><span className="bg-gradient-to-r from-[#172cff] via-[#1732ff] to-[#531cff] bg-clip-text text-transparent">Intelligence</span></h1><h2 className="mt-3 text-[20px] font-extrabold tracking-[-.8px] text-brand-dark">Smarter Data. Clearer Insights. Bigger Decisions.</h2><p className="mt-2 max-w-[535px] text-[15px] leading-[1.32] text-[#526294]">We help businesses unlock the true value of their data with AI-powered analytics, automation, and intelligence. Turn your data into actionable insights and drive faster, smarter, more profitable decisions.</p><div className="mt-3 flex flex-wrap gap-4"><a href="#contact" className="rounded-lg bg-gradient-to-r from-[#2412fd] to-[#122af0] px-6 py-3 text-xs font-bold text-white shadow-lg shadow-indigo-200">Book a Free Consultation →</a><a href="#how" className="rounded-lg border border-[#5365af] bg-white px-6 py-3 text-xs font-bold text-[#111b72]"><span className="mr-2 inline-flex rounded-full bg-[#e6edff] p-0.5 text-[#2738ff]"><Icon name="play" className="h-3 w-3"/></span>See It in Action</a></div></div>
        <div className="relative mx-auto h-[310px] w-full max-w-[610px] sm:h-[345px]">
          <div className="absolute left-[6%] top-[11%] z-10 w-[158px] rounded-xl bg-white p-4 shadow-xl shadow-blue-200/70"><p className="text-[10px] font-bold text-brand-dark">Total Data Value</p><p className="mt-1 text-xl font-extrabold text-brand-green">↑ 256%</p><div className="mt-2 flex h-11 items-end gap-2 border-b border-indigo-200 pb-1"><i className="w-3 rounded-t bg-indigo-200"/><i className="h-2 w-3 rounded-t bg-indigo-300"/><i className="h-4 w-3 rounded-t bg-indigo-400"/><i className="h-7 w-3 rounded-t bg-[#313bdb]"/><i className="h-9 w-3 rounded-t bg-[#1420d9]"/></div></div>
          <div className="absolute bottom-[1%] left-[3%] z-10 space-y-1.5">{[["pie","Predict Trends"],["file","Real-time Insights"],["gear","Automate Reporting"],["chart","Smarter Decisions"]].map(([i,t]) => <div key={t} className="flex w-[165px] items-center gap-2 rounded-lg bg-white px-2.5 py-2 shadow-lg shadow-blue-200/70"><span className="rounded-md bg-[#e8edff] p-1.5 text-[#1726ff]"><Icon name={i as IconName} className="h-4 w-4"/></span><span className="text-[10px] font-bold text-brand-dark">{t}</span></div>)}</div>
          <div className="absolute left-[29%] top-0 h-full w-[310px] overflow-hidden rounded-[42%] bg-gradient-to-b from-[#d9dbff] to-[#eef6ff]"><img className="h-full w-full object-cover object-[60%_30%] mix-blend-multiply" src="https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=720&q=85" alt="Business analyst"/></div>
          <div className="absolute right-0 top-[5%] z-10 w-[170px] rounded-xl bg-white p-4 shadow-xl shadow-blue-200/70"><p className="text-[14px] font-extrabold leading-[1.05] text-brand-dark">From Data<br/>to Real Growth</p>{["Uncover Opportunities", "Improve Efficiency", "Reduce Costs", "Make Data-Driven Decisions"].map(x => <p key={x} className="mt-2 flex items-center gap-1.5 text-[9px] text-[#435287]"><span className="rounded-full bg-green-100 p-0.5 text-green-600"><Icon name="check" className="h-3 w-3"/></span>{x}</p>)}</div>
          <div className="absolute bottom-[8%] right-0 z-10 w-[170px] rounded-xl bg-white p-3 shadow-xl shadow-blue-200/70"><p className="text-[12px] font-extrabold text-brand-dark">AI-Powered<br/>Analytics</p><svg viewBox="0 0 160 60" className="mt-1 h-12 w-full overflow-visible"><polyline points="0,48 14,38 28,45 45,22 61,36 78,18 93,31 111,12 130,42 148,27 158,3" fill="none" stroke="#1e27ff" strokeWidth="2"/><circle cx="158" cy="3" r="2" fill="#1e27ff"/></svg></div>
          <p className="absolute bottom-[-4px] right-[1%] z-20 rotate-[-9deg] font-hand text-[18px] leading-[.8] text-[#1726ff]">Your<br/>Data<br/>Our Intelligence</p>
        </div>
      </div>
      <div className="relative mt-5 grid max-w-[570px] grid-cols-3 gap-3 text-[#1926e7]"><Stat icon="chart" value="3x" label="Faster Insights"/><Stat icon="search" value="70%" label="Less Analysis Time"/><Stat icon="pie" value="5x" label="Better Decision Making"/></div>
    </section>
    <section className="mx-auto max-w-[1440px] px-6 py-3 lg:px-[76px]"><p className="text-[10px] font-extrabold tracking-[2.5px] text-[#1822e5]">TRUSTED DATA PLATFORMS &amp; TECHNOLOGIES</p><div className="mt-3 grid grid-cols-3 items-center gap-4 text-center sm:grid-cols-5 lg:grid-cols-9">{["Google BigQuery", "Snowflake", "aws Redshift", "Microsoft Fabric", "databricks", "Power BI", "Tableau", "Looker"].map((x,i) => <div key={x} className="text-[15px] font-medium text-[#1e306a]"><span className="mr-1 text-xl text-[#0876ed]">{["◆","✽","◡","▦","◇","▮","✣","♧"][i]}</span>{x}</div>)}</div></section>
    <section id="solutions" className="mx-auto max-w-[1440px] px-6 py-4 lg:px-[76px]"><SectionTitle eyebrow="OUR DATA INTELLIGENCE SOLUTIONS" title="End-to-End Data Intelligence for Your Business" subtitle="We combine data, AI, and automation to help you extract meaningful insights and drive real business impact."/><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{solutions.map(([icon,title,body],i) => <article key={title} className="group min-h-[144px] rounded-xl bg-[linear-gradient(135deg,#f7f9ff,#fff)] p-4 shadow-[0_5px_18px_rgba(35,77,155,.06)]"><span className={`inline-flex rounded-full p-3 ${["bg-indigo-100 text-indigo-700","bg-emerald-100 text-emerald-600","bg-violet-100 text-violet-700","bg-sky-100 text-sky-600","bg-indigo-100 text-indigo-700","bg-sky-100 text-sky-600","bg-blue-100 text-blue-700","bg-pink-100 text-pink-500"][i]}`}><Icon name={icon as IconName}/></span><h3 className="mt-2 text-[15px] font-extrabold tracking-[-.5px] text-brand-dark">{title}</h3><p className="max-w-[185px] text-[12px] leading-[1.16] text-[#506195]">{body}</p><span className="float-right -mt-6 rounded-full bg-white p-2 text-[#1429ff] shadow-lg"><Icon name="arrow" className="h-4 w-4"/></span></article>)}</div></section>
    <section id="how" className="mx-auto max-w-[1440px] px-6 py-1 lg:px-[76px]"><SectionTitle eyebrow="HOW IT WORKS" title="From Raw Data to Real Results" subtitle="A simple, proven process to help you unlock the power of your data."/><div className="mt-2 grid rounded-xl bg-[#fafbff] p-2 sm:grid-cols-5">{process.map(([icon,title,body],i) => <div key={title} className="relative px-4 py-3 text-center"><span className="mx-auto inline-flex rounded-full bg-[#e8edff] p-3 text-[#192cff]"><Icon name={icon as IconName}/></span><p className="mt-1 text-[9px] font-bold text-[#2030ff]">0{i+1}</p><h3 className="text-sm font-extrabold text-brand-dark">{title}</h3><p className="mx-auto max-w-[160px] text-[12px] leading-[1.15] text-[#536394]">{body}</p>{i<4&&<span className="absolute right-[-8px] top-8 hidden text-2xl text-[#192cff] sm:block">→</span>}</div>)}</div></section>
    <section className="mx-auto grid max-w-[1440px] gap-3 px-6 py-4 lg:grid-cols-2 lg:px-[76px]"><div><p className="text-[10px] font-extrabold tracking-[2.5px] text-[#1822e5]">REAL DATA. REAL BUSINESS IMPACT.</p><h2 className="text-[24px] font-extrabold tracking-[-1px] text-brand-dark">Data-Driven Businesses Grow Faster</h2><p className="text-[14px] leading-tight text-[#59689a]">See how companies like yours are making smarter decisions, reducing costs, and achieving higher growth with AI WorksForce.</p><div className="mt-3 grid grid-cols-4 gap-2">{[["chart","312%","Increased\nData Utilization"],["database","3x","Faster\nDecision Making"],["search","70%","Less Reporting\nTime"],["chart","5x","Higher\nBusiness Growth"]].map(([i,v,l])=><div key={v} className="rounded-xl bg-[#f8faff] p-2 text-center"><span className="inline-flex rounded-full bg-emerald-100 p-2 text-emerald-600"><Icon name={i as IconName} className="h-4 w-4"/></span><p className="mt-1 text-xl font-extrabold text-[#1221d4]">{v}</p><p className="whitespace-pre-line text-[10px] leading-tight text-[#536394]">{l}</p></div>)}</div></div><article className="rounded-xl bg-[#fafbff] p-3"><div className="grid grid-cols-[140px_1fr] gap-3"><img src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=450&q=80" className="h-[150px] w-full rounded-lg object-cover" alt="Analytics dashboard"/><div><p className="text-[9px] font-extrabold tracking-[2px] text-[#2834f1]">CASE STUDY</p><h3 className="text-[16px] font-extrabold leading-tight text-brand-dark">Retail Brand: Unlocking Growth with Data Intelligence</h3><p className="mt-1 text-[12px] leading-tight text-[#526294]">We helped a retail brand integrate their sales, marketing, and customer data to get real-time insights, resulting in 312% higher revenue growth in just 6 months.</p><div className="mt-2 flex gap-5"><b className="text-xl text-[#1626e5]">312%<small className="block text-[9px] font-medium text-[#58689a]">Revenue Growth</small></b><b className="text-xl text-[#1626e5]">70%<small className="block text-[9px] font-medium text-[#58689a]">Less Reporting Time</small></b><b className="text-xl text-[#1626e5]">5x<small className="block text-[9px] font-medium text-[#58689a]">Better Decisions</small></b></div></div></div></article></section>
    <section className="mx-auto grid max-w-[1440px] gap-5 px-6 py-2 lg:grid-cols-2 lg:px-[76px]"><div className="flex items-center gap-4 rounded-xl bg-[#fafbff] p-3"><img src="https://images.unsplash.com/photo-1531384441138-2736e62e0919?auto=format&fit=crop&w=180&q=85" alt="Amit Sharma" className="h-24 w-24 rounded-full object-cover"/><div><span className="text-4xl font-serif text-[#1830ff]">“</span><p className="text-[13px] leading-tight text-[#536394]">AI WorksForce helped us turn our scattered data into clear, actionable insights. We now make faster decisions and have seen significant growth in our business.</p><p className="mt-2 text-sm font-extrabold text-brand-dark">Amit Sharma</p><p className="text-[11px] text-[#536394]">CTO, GrowthTech (Retail)</p></div></div><div className="border-l border-blue-100 pl-4"><p className="text-[10px] font-extrabold tracking-[2px] text-[#1822e5]">WORKS WITH YOUR EXISTING DATA</p><div className="mt-2 grid grid-cols-5 gap-2">{["Google BigQuery","Snowflake","Redshift","PostgreSQL","MySQL"].map(x=><div key={x} className="rounded-lg bg-[#fafbff] px-2 py-4 text-center text-[9px] font-bold text-[#506195]">{x}</div>)}</div></div></section>
    <section id="contact" className="mx-auto mt-3 max-w-[1440px] px-3"><div className="relative overflow-hidden rounded-xl bg-[linear-gradient(110deg,#062269,#1422e9,#092d9f)] px-6 py-7 text-center text-white"><p className="text-[9px] font-bold tracking-[3px]">READY TO TURN YOUR DATA INTO GROWTH?</p><h2 className="mt-2 text-[22px] font-extrabold">Let’s Build a Data-Driven Future Together</h2><p className="text-[12px] text-blue-100">Get expert guidance on how our AI solutions can unlock the full potential of your data.</p><div className="mt-4 flex justify-center gap-3"><a href="#" className="rounded-md bg-white px-6 py-3 text-[11px] font-bold text-[#102079]">Book a Free Consultation →</a><a href="#solutions" className="rounded-md border border-white/70 px-6 py-3 text-[11px] font-bold">Explore Data Solutions</a></div><p className="absolute bottom-3 right-9 rotate-[-10deg] font-hand text-lg leading-none text-white">More Insights<br/>Better Decisions<br/>Bigger Growth</p></div></section>
    <footer className="mx-auto max-w-[1440px] px-8 py-4 text-[#58689a]"><div className="flex flex-wrap items-end justify-between gap-4 border-b border-blue-100 pb-3"><div><p className="text-lg font-extrabold text-[#071a7a]">AI WorksForce</p><p className="text-[8px] font-semibold">Automate. Accelerate. Grow.</p></div><div className="flex flex-wrap gap-x-5 gap-y-2 text-[9px]">{nav.map(x=><a href="#" key={x}>{x}</a>)}</div><div className="flex gap-3 text-[#173077]">{(["linkedin","twitter","youtube","instagram"] as IconName[]).map(x=><a href="#" key={x}><Icon name={x} className="h-4 w-4"/></a>)}</div></div><div className="flex justify-between pt-3 text-[9px]"><span>© 2024 AI WorksForce. All rights reserved.</span><span className="space-x-5"><a href="#">Privacy Policy</a><a href="#">Terms of Service</a><a href="#">Contact</a></span></div></footer>
  </main>;
}

function Stat({ icon, value, label }: { icon: IconName; value: string; label: string }) { return <div className="flex items-center gap-2"><span className="rounded-full bg-emerald-100 p-3 text-emerald-500"><Icon name={icon}/></span><div><b className="block text-xl leading-none">{value}</b><span className="text-[10px] font-medium text-[#58689a]">{label}</span></div></div>; }
function SectionTitle({ eyebrow, title, subtitle }: { eyebrow: string; title: string; subtitle: string }) { return <div className="text-center"><p className="text-[10px] font-extrabold tracking-[2.5px] text-[#1822e5]">{eyebrow}</p><h2 className="text-[23px] font-extrabold tracking-[-1px] text-brand-dark">{title}</h2><p className="text-[13px] text-[#58689a]">{subtitle}</p></div>; }
